environment: dev
    
redis_host: master.maturro-dev-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 1
  replicas: 1

secret:
  redis_pass: automate-all-the-things-dev
